# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The bear's lair
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The bear's lair is a public collection of RNA-seq papers combined with
  live analysis done by Kallisto and Sleuth. Our aim is to make RNA-seq
  data and analysis both publicly available and easy to view without
  multiple processors.
baseurl: "/lair" # the subpath of your site, e.g. /blog
url: "http://pachterlab.github.io" # the base hostname & protocol for your site
github_username:  jekyll
keep_files: ["_data", "_images", "_datatables"]
include: ["_data", "_images", "_datatables"]

# Build settings
markdown: kramdown

# Collections
collections:
- analysis
